### ISSUE TITLE
Failure to read or write for CC2531 chips

### ISSUE THREAD

**Issue by xaviergr** [Larsjep/CCLib-ESP32#1]
Hello, I am trying to flash a CC2531 dongle with an ESP32-WROOM programmed via the Arduino IDE CCLib example.

Getting the chip information with cc_info.py works as expected:
```
Chip information:
      Chip ID : 0xb524
   Flash size : 256 Kb
    Page size : 2 Kb
    SRAM size : 8 Kb
          USB : Yes

Device information:
 IEEE Address : xxxxxxxxxxxx
           PC : 0000

Debug status:
 [ ] CHIP_ERASE_BUSY
 [ ] PCON_IDLE
 [X] CPU_HALTED
 [ ] PM_ACTIVE
 [ ] HALT_STATUS
 [ ] DEBUG_LOCKED
 [X] OSCILLATOR_STABLE
 [ ] STACK_OVERFLOW

Debug config:
 [ ] SOFT_POWER_MODE
 [ ] TIMERS_OFF
 [X] DMA_PAUSE
 [X] TIMER_SUSPEND
```

Reading results in the following error:
```
INFO: Found a CC2531 chip on /dev/ttyUSB0

Chip information:
      Chip ID : 0xb524
   Flash size : 256 Kb
    Page size : 2 Kb
    SRAM size : 8 Kb
          USB : Yes

Reading 256 KBytes to CC2531_factory_firmware.hex...
Traceback (most recent call last):
  File "/home/xavier/CCLib-ESP32/Python/./cc_read_flash.py", line 41, in <module>
    chunk = dbg.readCODE( i * 0x1000, 0x1000 )
  File "/home/xavier/CCLib-ESP32/Python/cclib/chip/cc254x.py", line 154, in readCODE
    return self.readXDATA( 0x8000 + offset, size )
  File "/home/xavier/CCLib-ESP32/Python/cclib/chip/cc254x.py", line 122, in readXDATA
    return bytearray(self.burstReadCode(size));
  File "/home/xavier/CCLib-ESP32/Python/cclib/ccproxy.py", line 358, in burstReadCode
    raise IOError(f"Invalid size of burst read: {length}, max {bufferSize}")
OSError: Invalid size of burst read: 4096, max 2048
```

And writing fails as well:
```
INFO: Found a CC2531 chip on /dev/ttyUSB0

Chip information:
      Chip ID : 0xb524
   Flash size : 256 Kb
    Page size : 2 Kb
    SRAM size : 8 Kb
          USB : Yes
Sections in CC2531ZNP-Prod.hex:

 Addr.    Size
-------- -------------
 0x0000   8176 B
 0x1ff6   10 B
 0x3fff0   1 B
 0x2000   239616 B

This is going to ERASE and REPROGRAM the chip. Are you sure? <y/N>:  y

Flashing:
 - Chip erase...
 - Flashing 4 memory blocks...
 -> 0x0000 : 8176 bytes
    Progress 0%...  ERROR: CCDebugger responded with an error (0x04) (1024)
Traceback (most recent call last):
  File "/home/xavier/CCLib-ESP32/Python/./cc_write_flash.py", line 104, in <module>
    dbg.writeCODE( mb.addr + offset, mb.bytes, verify=True, showProgress=True )
  File "/home/xavier/CCLib-ESP32/Python/cclib/chip/cc254x.py", line 552, in writeCODE
    self.brustWrite( data[iOfs:iOfs+iLen] )
  File "/home/xavier/CCLib-ESP32/Python/cclib/ccproxy.py", line 348, in brustWrite
    self.debugStatus = self.readFrame()
  File "/home/xavier/CCLib-ESP32/Python/cclib/ccproxy.py", line 182, in readFrame
    raise IOError("CCDebugger responded with an error (0x%02x) (%d)" % (bL, (bL << 8) | bH))
OSError: CCDebugger responded with an error (0x04) (1024)
```

Any hints on how to resolve these issues, would be very welcome.

**Comment by xaviergr** [comment]
By hacking the python scripts further I managed to flash the device successfully by reducing the flashPageSize and bulkBlockSize variables from 2048 to 256 bytes.

Reading also seemed to work by reducing the read length to the maximum needed of 2048 bytes instead of 4096. Although after reading all data, it then fails when trying to write to the output file for some other reason.

Here are the modifications that I tried:

```
diff --git a/Python/cc_read_flash.py b/Python/cc_read_flash.py
index 72985ab..3e88b14 100755
--- a/Python/cc_read_flash.py
+++ b/Python/cc_read_flash.py
@@ -38,7 +38,7 @@ hexFile = CCHEXFile(opts['out'])
 for i in range(0, int(dbg.chipInfo['flash'] / 4)):

        # Read CODE
-       chunk = dbg.readCODE( i * 0x1000, 0x1000 )
+       chunk = dbg.readCODE( i * 0x800, 0x800 )

        # Write chunk to file
        hexFile.stack(chunk)
diff --git a/Python/cclib/chip/cc254x.py b/Python/cclib/chip/cc254x.py
index 18579ce..91bd64e 100644
--- a/Python/cclib/chip/cc254x.py
+++ b/Python/cclib/chip/cc254x.py
@@ -102,9 +102,9 @@ class CC254X(ChipDriver):

                # Populate variables
                self.flashSize = self.chipInfo['flash'] * 1024
-               self.flashPageSize = 0x800
+               self.flashPageSize = 0x100
                self.sramSize = self.chipInfo['sram'] * 1024
-               self.bulkBlockSize = 0x800
+               self.bulkBlockSize = 0x100


        ###############################################
```
